version: "3.9"

services:
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    restart: always
    ports:
      - "16686:16686"
      - "6831:6831"
      
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  stock:
    build:
      context: stock
    restart: always
    environment:
      - JAEGER_ADDRESS=jaeger
      - JAEGER_PORT=6831
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - jaeger
      - rabbitmq    

  checkout:
    build:
      context: checkout
    restart: always
    ports:
      - "8080:8080"
    environment:
      - JAEGER_ADDRESS=jaeger
      - JAEGER_PORT=6831
      - GRPC_ADDRESS=checkout:8080
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - jaeger
      - rabbitmq        

  gateway:
    build:
      context: gateway
    restart: always
    ports:
      - "8081:8081"
    environment:
      - JAEGER_ADDRESS=jaeger
      - JAEGER_PORT=6831
      - CHECKOUT_SERVICE_ADDRESS=checkout:8080
      - HTTP_ADDRESS=:8081
    depends_on:
      - jaeger
      - checkout

  

  
